### ISSUE TITLE
Setup integration between GitHub and Google to enable CI

### ISSUE THREAD

**Issue by alecfrancesconi** [Data4Democracy/ati-broadcastapp#6]
Need to connect our GitHub repository to Google Cloud Platform to enable continuous integration process while we develop/test/deploy

**Comment by lilianhj** [comment]
Here's my research:

**_ASSUMPTIONS:_**

- We’re fine with hosting on GitHub rather than on our own servers (which might be better for data security, but would be more difficult and costly to manage)
- The code will be open-source
- The app will be written in Python or some flavor of Javascript

**_OPTIONS:_**

**Travis CI:**
Features/Requirements: Very easy to get started, only integrates with GitHub, needs to be used with public repositories; supports Android, C, C++, Clojure, Erlang, Go, Groovy, Haskell, Java, Javascript (with Node.js), Objective-C, Perl, PHP, Python, Ruby, Rust, Scala, Swift, etc
Cost: Free for open-source projects
Links: [https://travis-ci.org/](https://travis-ci.org/), [https://github.com/integrations/travis-ci](https://github.com/integrations/travis-ci)

**Jenkins:**
Features/Requirements: Java-based tool so Java Runtime Environment is needed to run it, robust developer community, high customization with over 400 plugins, can integrate with GitHub, GitLab, Virtual Studio, etc; supports Python, Ruby, Java, Android, C/C++
Cost: Free
Links: [https://jenkins.io/](https://jenkins.io/), [https://blog.appliedis.com/2016/11/08/continuous-integration-with-jenkins-and-github/](https://blog.appliedis.com/2016/11/08/continuous-integration-with-jenkins-and-github/), [https://jenkins.io/solutions/github/](https://jenkins.io/solutions/github/)

**CircleCI:** 
Features/Requirements: Can integrate with GitHub and Bitbucket; supports Go (Golang), Haskell, Java, Node.js, PHP, Python, Ruby/Rails, Scala
Cost: Free option allows infinite repos, infinite users, 1,500 build minutes per month, 1 container, 1 concurrent build
Links: [https://circleci.com/](https://circleci.com/)

**Codeship:**
Features/Requirements: Can integrate with GitHub, Bitbucket, and GitLab; supports Dart, Elixir, Go, Java and JVM based languages, PHP, Python, Node.JS, Ruby
Cost: Free plan allows 100 builds/month, 1 concurrent build, 1 parallel test pipeline, unlimited projects and users
Links: [https://codeship.com/](https://codeship.com/)

**_VERDICT:_**
Travis CI and Jenkins seem better suited to our needs, as they are more established and also have more developed open-source ecosystems/support, rather than just offering a free option that acts as a lead-in to the paid plans.
Of those two, it looks like Travis CI is better if we just want to get things up and running fast, and if we’re sure we want to host the code on GitHub for the foreseeable future; Jenkins seems to offer more power and flexibility if we need it, but that requires extending its features through plugins, etc, whereas Travis CI is the more “vanilla”, simpler approach, and makes it faster to get started.
**Tutorial for linking Travis CI with Google Cloud:** [https://cloud.google.com/solutions/continuous-delivery-with-travis-ci](https://cloud.google.com/solutions/continuous-delivery-with-travis-ci)

**Comment by jonganc** [comment]
@alecfrancesconi  I think we can close this, no?

**Comment by jonganc** [comment]
@alecfrancesconi Ignore last comment. I'll just go ahead and close it and, if you disagree, we can repopoen.
